spring:
  application:
    name: follows
  devtools:
    restart:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/follows}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]
      base-path: /actuator
  endpoint:
    prometheus:
      access: read_only
  metrics:
    tags:
      application: follows

springdoc:
  show-actuator: true

instagram:
  username: ##########
  password: ##########